DROP TABLE IF EXISTS annonce;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(64) NOT NULL UNIQUE,
	email VARCHAR(64) NOT NULL UNIQUE,
	password_hash VARCHAR(512) NOT NULL,
	roles VARCHAR(128) NOT NULL DEFAULT 'USER',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	label VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE annonce (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	title VARCHAR(64) NOT NULL,
	description VARCHAR(256) NOT NULL,
	adress VARCHAR(64) NOT NULL,
	mail VARCHAR(64) NOT NULL,
	date TIMESTAMP NOT NULL,
	status VARCHAR(16) NOT NULL,
	version BIGINT NOT NULL DEFAULT 0,
	user_id BIGINT NOT NULL,
	category_id BIGINT NOT NULL,
	CONSTRAINT fk_annonce_user FOREIGN KEY (user_id) REFERENCES "user"(id),
	CONSTRAINT fk_annonce_category FOREIGN KEY (category_id) REFERENCES category(id),
	CONSTRAINT ck_annonce_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX idx_annonce_date ON annonce(date);
CREATE INDEX idx_annonce_status ON annonce(status);
CREATE INDEX idx_annonce_category_status ON annonce(category_id, status);
CREATE INDEX idx_annonce_title ON annonce(title);
